[package]
name = "syndicate-rs"
version = "0.1.0"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

[dependencies]
preserves = "0.3.0"

serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11"

tokio = "0.2.0-alpha"
bytes = "0.4.12"

futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }
