[package]
name = "syndicate-rs"
version = "0.2.0"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

[patch.crates-io]
preserves = { path = "/home/tonyg/src/preserves/implementations/rust/preserves" }
preserves-schema = { path = "/home/tonyg/src/preserves/implementations/rust/preserves-schema" }

[features]
vendored-openssl = ["openssl/vendored"]

[profile.release]
debug = true
# lto = true

[lib]
name = "syndicate"

[build-dependencies]
preserves-schema = "0.3.0"

[dependencies]
preserves = "0.16.0"
preserves-schema = "0.3.0"

serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11"

tokio = { version = "1.7.1", features = ["macros", "sync", "net", "rt", "rt-multi-thread", "time"] }
tokio-util = "0.6.7"
bytes = "1.0.1"

futures = "0.3.5"

getrandom = "0.2.3"
hmac = "0.11.0"
sha2 = "0.9.5"

structopt = "0.3.14"

tungstenite = "0.13.0"
tokio-tungstenite = "0.14.0"

tracing = "0.1.14"
tracing-subscriber = "0.2.5"
tracing-futures = "0.2.4"

# Only used for vendored-openssl, which in turn is being used for cross-builds
openssl = { version = "0.10", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_dataspace"
harness = false
