cargo-features = ["strip"]

[workspace]
members = [
  "syndicate",
  "syndicate-macros",
  "syndicate-server",
  ]

# [patch.crates-io]
# preserves = { path = "../preserves/implementations/rust/preserves" }
# preserves-schema = { path = "../preserves/implementations/rust/preserves-schema" }

[profile.release]
strip = true
# debug = true
# lto = true
