[package]
name = "syndicate-rs"
version = "0.1.0"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

[lib]
name = "syndicate"

[dependencies]
preserves = "0.3.1"

serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11"

tokio = { version = "0.2.20", features = ["macros", "rt-threaded", "sync", "dns", "tcp", "time", "stream"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
bytes = "0.5.4"

futures = "0.3.4"
