[package]
name = "syndicate-rs"
version = "0.1.0"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

[features]
vendored-openssl = ["openssl/vendored"]

[profile.release]
debug = true

[lib]
name = "syndicate"

[dependencies]
preserves = "0.6.0"

serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11"

tokio = { version = "0.2.21", features = ["macros", "rt-threaded", "sync", "dns", "tcp", "time", "stream"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
bytes = "0.5.4"

futures = "0.3.5"

structopt = "0.3.14"

tungstenite = "0.10.1"
tokio-tungstenite = "0.10.1"

tracing = "0.1.14"
tracing-subscriber = "0.2.5"
tracing-futures = "0.2.4"

# Only used for vendored-openssl, which in turn is being used for cross-builds
openssl = { version = "0.10", optional = true }
