[workspace]
members = [
  "syndicate",
  ]

[patch.crates-io]
preserves = { path = "/home/tonyg/src/preserves/implementations/rust/preserves" }
preserves-schema = { path = "/home/tonyg/src/preserves/implementations/rust/preserves-schema" }

[profile.release]
debug = true
# lto = true
