[package]
name = "syndicate-tools"
version = "0.2.1"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

description = "Syndicate command-line utilities."
homepage = "https://syndicate-lang.org/"
repository = "https://git.syndicate-lang.org/syndicate-lang/syndicate-rs"
license = "Apache-2.0"

[dependencies]
preserves = "3.0"
syndicate = { path = "../syndicate", version = "0.24"}

clap = { version = "^4.0", features = ["derive"] }
clap_complete = "^4.0"

[package.metadata.workspaces]
independent = true
