[package]
name = "syndicate-server"
version = "0.9.2"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

description = "Dataspace server."
homepage = "https://syndicate-lang.org/"
repository = "https://git.syndicate-lang.org/syndicate-lang/syndicate-rs"
license = "Apache-2.0"

[build-dependencies]
preserves-schema = "0.8.0"

[dependencies]
preserves-schema = "0.8.0"
syndicate = { path = "../syndicate", version = "^0.10.0"}
syndicate-macros = { path = "../syndicate-macros", version = "^0.4.0"}

futures = "0.3.5"

notify = "4.0.17"

structopt = "0.3.14"

tungstenite = "0.13.0"
tokio-tungstenite = "0.14.0"

tokio = { version = "1.10.0", features = ["io-std", "time"] }
tokio-util = "0.6.7"

tracing = "0.1.14"
tracing-subscriber = "0.2.5"
tracing-futures = "0.2.4"
