[package]
name = "syndicate-server"
version = "0.2.0"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

description = "Dataspace server."
homepage = "https://syndicate-lang.org/"
repository = "https://git.syndicate-lang.org/syndicate-lang/syndicate-rs"
license = "Apache-2.0"

[dependencies]
syndicate = { path = "../syndicate", version = "^0.2.0" }
syndicate-macros = { path = "../syndicate-macros", version = "^0.2.0" }

futures = "0.3.5"

structopt = "0.3.14"

tungstenite = "0.13.0"
tokio-tungstenite = "0.14.0"

tokio = { version = "1.10.0", features = ["io-util", "macros", "sync", "net", "rt", "rt-multi-thread", "time"] }
tokio-util = "0.6.7"

tracing = "0.1.14"
tracing-subscriber = "0.2.5"
tracing-futures = "0.2.4"
