[package]
name = "syndicate-server"
version = "0.32.1"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

description = "Dataspace server."
homepage = "https://syndicate-lang.org/"
repository = "https://git.syndicate-lang.org/syndicate-lang/syndicate-rs"
license = "Apache-2.0"

[features]
jemalloc = ["dep:tikv-jemallocator"]

[build-dependencies]
preserves-schema = "3.2"
syndicate = { path = "../syndicate", version = "0.28.0"}

[dependencies]
preserves-schema = "3.2"
syndicate = { path = "../syndicate", version = "0.28.0"}
syndicate-macros = { path = "../syndicate-macros", version = "0.23.1"}

chrono = "0.4"
futures = "0.3"
lazy_static = "1.4"
noise-protocol = "0.1"
noise-rust-crypto = "0.5"
notify = "4.0"
structopt = "0.3"

tikv-jemallocator = { version = "0.5.0", optional = true }

tungstenite = "0.13"
tokio-tungstenite = "0.14"

tokio = { version = "1.10", features = ["io-std", "time", "process"] }
tokio-util = "0.6"

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[package.metadata.workspaces]
independent = true
