[package]
name = "syndicate-server"
version = "0.10.0"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

description = "Dataspace server."
homepage = "https://syndicate-lang.org/"
repository = "https://git.syndicate-lang.org/syndicate-lang/syndicate-rs"
license = "Apache-2.0"

[build-dependencies]
preserves-schema = "1.0.0"

[dependencies]
preserves-schema = "1.0.0"
syndicate = { path = "../syndicate", version = "^0.11.0"}
syndicate-macros = { path = "../syndicate-macros", version = "^0.5.0"}

futures = "0.3"

notify = "4.0"

structopt = "0.3"

tungstenite = "0.13"
tokio-tungstenite = "0.14"

tokio = { version = "1.10", features = ["io-std", "time"] }
tokio-util = "0.6"

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
