[package]
name = "syndicate"
version = "0.8.0"
authors = ["Tony Garnock-Jones <tonyg@leastfixedpoint.com>"]
edition = "2018"

description = "Syndicated Actor model for Rust, including network communication and Dataspaces."
homepage = "https://syndicate-lang.org/"
repository = "https://git.syndicate-lang.org/syndicate-lang/syndicate-rs"
license = "Apache-2.0"

[features]
vendored-openssl = ["openssl/vendored"]

[build-dependencies]
preserves-schema = "0.5.0"

[dependencies]
preserves = "0.17.1"
preserves-schema = "0.5.0"

tokio = { version = "1.10.0", features = ["io-util", "macros", "sync", "net", "rt", "rt-multi-thread", "time"] }
tokio-util = "0.6.7"
bytes = "1.0.1"

futures = "0.3.5"

getrandom = "0.2.3"
hmac = "0.11.0"
sha2 = "0.9.5"

tracing = "0.1.14"
tracing-subscriber = "0.2.5"
tracing-futures = "0.2.4"

# Only used for vendored-openssl, which in turn is being used for cross-builds
openssl = { version = "0.10", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_dataspace"
harness = false
