#!/bin/sh
TASKSET='taskset -c 0,1'
if [ $(uname -s) = 'Darwin' ]
then
    TASKSET=
fi
make -C ../syndicate-server binary && exec $TASKSET ../target/release/syndicate-server -c benchmark-config.pr "$@"
